services:
  simulation:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/app
    network_mode: host
    stdin_open: true
    tty: true 